# This is a basic workflow to help you get started with Actions

name: Windows Build and Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Build Dependencies
        shell: powershell
        run: |
          pwd
          ls
          cd ..

          pwd
          ls

      - name: Build Project
        shell: bash
        run: |
          echo BUILD THE PROJECT
        
      - name: Install Test Dependencies
        shell: bash
        run: |
          echo INSTALL TEST DEPENDENCIES
        
      - name: Test Project
        shell: bash
        run: |
          echo TEST PROJECT
        
